# fly.toml app configuration file generated for subtitles-ai on 2025-02-02T22:50:53+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'subtitles-ai'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '4001'
  PYTHON_MODULE = 'main:app'

[processes]
  web = 'uvicorn main:app --host 0.0.0.0 --port 4001 --timeout-graceful-shutdown 120 --workers 4'

[http_service]
  internal_port = 4001
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['web']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 10000
    soft_limit = 8000

  [[http_service.checks]]
    interval = "10s"
    grace_period = "30s"
    timeout = "2s"
    method = "get"
    path = "/health"
    protocol = "http"

[[vm]]
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 2048
